package metrics

import (
	"github.com/prometheus/client_golang/prometheus"
)

var (
	labels = []string{"provider", "model", "endpoint", "api_format"}

	ProbeSuccess = prometheus.NewGaugeVec(prometheus.GaugeOpts{
		Name: "llm_probe_success",
		Help: "Whether the last probe was successful (1 = success, 0 = failure).",
	}, labels)

	ProbeDuration = prometheus.NewHistogramVec(prometheus.HistogramOpts{
		Name:    "llm_probe_duration_seconds",
		Help:    "Total request duration in seconds.",
		Buckets: []float64{0.1, 0.25, 0.5, 1, 2.5, 5, 10, 20, 30, 60},
	}, labels)

	ProbeConnectDuration = prometheus.NewHistogramVec(prometheus.HistogramOpts{
		Name:    "llm_probe_connect_duration_seconds",
		Help:    "Connection setup duration (DNS + TCP + TLS) in seconds.",
		Buckets: []float64{0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1, 2.5, 5},
	}, labels)

	ProbeTTFT = prometheus.NewHistogramVec(prometheus.HistogramOpts{
		Name:    "llm_probe_ttft_seconds",
		Help:    "Time to first token in seconds.",
		Buckets: []float64{0.05, 0.1, 0.25, 0.5, 1, 2.5, 5, 10, 20},
	}, labels)

	ProbeInputTokens = prometheus.NewGaugeVec(prometheus.GaugeOpts{
		Name: "llm_probe_input_tokens",
		Help: "Input (prompt) tokens consumed by the last probe.",
	}, labels)

	ProbeOutputTokens = prometheus.NewGaugeVec(prometheus.GaugeOpts{
		Name: "llm_probe_output_tokens",
		Help: "Output (completion) tokens generated by the last probe.",
	}, labels)

	ProbeTotalTokens = prometheus.NewGaugeVec(prometheus.GaugeOpts{
		Name: "llm_probe_total_tokens",
		Help: "Total tokens consumed by the last probe.",
	}, labels)

	ProbeTokenRate = prometheus.NewGaugeVec(prometheus.GaugeOpts{
		Name: "llm_probe_token_rate",
		Help: "Output token generation rate (tokens/second).",
	}, labels)

	ProbeErrors = prometheus.NewCounterVec(prometheus.CounterOpts{
		Name: "llm_probe_errors_total",
		Help: "Total number of probe errors by type.",
	}, append(labels, "error_type"))
)

func Register(reg prometheus.Registerer) {
	reg.MustRegister(
		ProbeSuccess,
		ProbeDuration,
		ProbeConnectDuration,
		ProbeTTFT,
		ProbeInputTokens,
		ProbeOutputTokens,
		ProbeTotalTokens,
		ProbeTokenRate,
		ProbeErrors,
	)
}
